@echo off
echo Starting EcoFuel Connect Application...
echo.
echo Starting Backend Server...
cd backend
start "Backend Server" cmd /k "npm start"
cd ..
echo.
echo Waiting 3 seconds for backend to start...
timeout /t 3 /nobreak > nul
echo.
echo Starting Frontend Application...
npm start